### ISSUE TITLE
admin is blank

### ISSUE THREAD

**Issue by jespersgaard** [sajadk/Laravel-starter-kit-with-oath-with-bootstrap3#1]
hello 

when i try and login to admin the page is just blank with a black topbar

rgds Martin

**Comment by sajadk** [comment]
It is just a starter kit only..!! not a complete application
anybody can clone and start their work..!! 
rgds Sajad

**Comment by sajadk** [comment]
@jespersgaard i am closing this issue as it is just a starter kit only.
